name = "Indonesia" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "Indonesia.vnm.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.Indonesia.vnm.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.Indonesia.vnm.my.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.Indonesia.vnm.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.Indonesia.vnm.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "47e8b4ea-3c98-42bb-b505-7576b1f698e2"
